# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmtaoUvCxXapGp6bVn27bPQJctfwsNn4

# Solicitar um numero inteiro positivo N ao usuario. Imprimir os numeros de N a 1. Realizar o exercicio usando loops for e while
"""

T = int(input("Entre com numero inteiro maior que 1: "))

#FOR
print("For")
for t in range(T):
  print(f"{T - t}", end= " ")
print()

#WHILE
i = 0
print("While")
while i < T :
  print(f"{T - i}", end= " ")
  i += 1

"""# Solicitar um número inteiro positivo N ao usuário. Imprimir os números de N a 1 trocando o sinal dos números. Realizar o exercício usando loops for e while. Exemplo para N igual a 5:"""

T = int(input("Entre com numero inteiro maior que 1: "))

#FOR
print("For: ")
for t in range(T):
  print(f"{t - T}", end = " ")
print("\n")

#WHILE
print("While: ")
i = 0

while i < T:
  print(f"{i - T}", end = " ")
  i += 1

"""# Solicitar um numero inteiro positivo N ao usuario e imprimir i² para o 0 < i < N. Por exemplo, para n = 5, serao impressos:
# 1
# 4
# 9
# 16
"""

N = int(input("Entre com numero inteiro maior que 1: "))

#FOR
print("For: ")
for i in range(1, N):
  print(f"{i*i}", end = " ")
print("\n")

#WHILE
print("While: ")
i = 1
while i < N :
  print(f"{i*i}")
  i += 1

"""5. Solicitar uma palavra ao usuário e dizer se a palavra é um palíndromo, isto é, pode ser lida
igualmente da esquerda para a direita e vice-versa. Exemplos de palavras que são palíndromos:
ovo, radar, mirim, arara, reviver. Algumas dicas:
"""

for x in range(palavra):
  palavra = str(input("Escreva uma palavra: "))
  invertido = palavra[::-1]
  if palavra == invertido:
    True
    print("A palavra é um palíndromo")
    print(palavra)
    print(invertido)
  else:
    False
    print("A palavra não é um palíndromo")
    print(palavra)
    print(invertido)

"""6. Fazer um programa que solicita um número inteiro positivo N ao usuário e imprime o seguinte
padrão na tela. Por exemplo, para
"""

N = int(input("Escreva um numero inteiro: "))
print("")
#FOR
print("For")
for n in range(N):
  print(f"N = {n  + 1} :")
  print("")

  print((" " + "-" * (n + 1)))
  print((("\n|" + (" " * (n + 1)) + "|\n") * (n + 1)))
  print((" " + "-" * (n + 1)))

  print("")

#WHILE
print("While")
i = 0
while i < N:
  print(f"N = {N} :")
  print("")

  print((" " + "-" * (N)))
  print((("\n|" + (" " * (N)) + "|\n") * (N)))
  print((" " + "-" * (N)))

  break

"""7. Fazer um programa que solicita um número inteiro positivo N ao usuário e imprime o seguinte
padrão na tela. Por exemplo, para N = 5:
"""

N = int(input("Escreva um numero inteiro: "))
print("")

for i in range(N):
  print("+" * (i + 1))
  print("")