# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LcBFq-GSFhD9fvm0FKi1jAI2i62XJQ_r

# 1. Faça um programa que leia 5 números e informe o maior número.
"""

numero_maior = float("-inf")

for x in range(5) :
  numero = float(input(f"Digite o {x+1}º numero: "))
  if numero > numero_maior:
    numero_maior = numero

  print(f"Maior numero digitado é {numero_maior}")

"""# 2. Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzam resto igual a 2."""

for x in range(1000, 2001) :
  if x % 11 == 2 :
    print(x)

"""# 3. Faça um programa que leia 5 números e informe a soma e a média dos números."""

soma = 0

for x in range(5) :
  numero = float(input(f"Digite o {x+1}º numero: "))
  soma += numero
  media = (soma / 5)

print(f"a soma dos numeros inseridos sera {soma} e sua média será: {media}")

"""# 4. Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número."""

numero = int(input("Digite um numero que voce nao saiba a tabuada\n"))

print(f"Tabuada de {numero}")

for tabuada in range(1,11):
  resultado = numero * tabuada
  print(f"{numero} x {tabuada} = {resultado}")

"""# 5. Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição."""

for i in range(1, 11):
    print(f"Tabuada do {i}:")
    for j in range(1, 11):
        resultado = i * j
        print(f"{i} x {j} = {resultado}")

"""# 6. Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro."""

for contador in range(1,21):
  print(contador)

print(list(range(1,21)))

"""# 7. Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50."""

for x in range(1,51):
  if x % 2 == 1:
    print(x)

"""# 8. Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles."""

num1 = int(input("Digite o primeiro número inteiro: "))
num2 = int(input("Digite o segundo número inteiro: "))

for intervalo in range(num1, num2 + 1):
  print(f"{intervalo}")

"""# 9. Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o faturamento."""

faturamentoB = 54000
soma = 0

for faturamento in range(5):
  faturamento = float(input(f"Digite o valor do {faturamento+1}º cliente: "))
  soma += faturamento

if soma > faturamentoB :
  print(f"O faturamento da loja A foi maior, sendo {soma}")

else :
  print(f"O faturamento da loja A foi menor, sendo {soma}")

"""# 10. Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

numeros_pares = 0
numeros_impares = 0

for x in range(10):
    numero = int(input(f"Digite o {x+1}º número inteiro: "))

    if numero % 2 == 0:
        numeros_pares += 1

    else:
        numeros_impares += 1

print(f"Quantidade de números pares: {numeros_pares}")
print(f"Quantidade de números ímpares: {numeros_impares}")

"""# 11. Um funcionário de uma empresa recebe aumento salarial anualmente Sabe-se que:
# Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
# Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
# A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.
"""

salario_1995 = float(input("Digite o salário inicial do funcionário em 1995: R$ "))
porcentagem = 1.5

for ano in range(1996, 2023):
    porcentagem_aplicada = (porcentagem / 100) * salario_1995
    salario_final = salario_1995 + porcentagem_aplicada
    salario_1995 = salario_final
    print(f"Salario em {ano}: R$ {salario_final}")
    porcentagem *= 2

"""# 12. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido."""

while True:
  nota = float(input("Digite uma nota entre 0 a 10:\n"))
  if nota >= 0 and nota <= 10 :
    break
  else :
   print("Nota invalida")

"""# 13. Uma loja tem tem uma política de descontos de acordo com o valor da compra do cliente. Os descontos começam acima dos R$500. A cada 100 reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até 25%.
# Por exemplo: R$500 = 1% || R$600,00 = 2% … etc…
# Faça um programa que exiba essa tabela de descontos no seguinte formato:
# Valordacompra – porcentagem de desconto – valor final

"""

valor = float(input("Digite o valor do produto: RS"))

if valor >= 600:
  reduzido = valor - 500
  if  reduzido >= 100:
    for x in range(999):
      contador += 1
      reduzido -= 100
      if reduzido > 100 or contador == 24:
        break

porcentagem = contador / 100
desconto = valor * porcentagem
final = valor - desconto
print(f"O produto de RD{valor} ficara a partir de {final} com o desconto de {desconto}")

"""# 14. Faça um programa que receba a idade de 15 pessoas e que calcule e mostre:
# a) A quantidade de pessoas em cada faixa etária;
# b) A percentagem de pessoas na primeira e na última faixa etária, com relação
# ao total de pessoas:
#  Até 15 anos
#  De 16 a 30 anos
#  De 31 a 45 anos
#  De 46 a 60 anos
#  Acima de 61 anos

"""

ate_15 = 0
de16_ate30 = 0
de31_ate45 = 0
de46_ate60 = 0
acima61 = 0

for pessoas in range (5):
  idade = int(input(f"Digite a idade da pessoa{pessoas+1}: "))
  if idade <= 15:
    ate_15 += 1
  elif idade >= 16 and idade <= 30:
    de16_ate30 += 1
  elif idade >= 31 and idade <= 45:
    de31_ate45 += 1
  elif idade >= 46 and idade <= 60:
    de46_ate60 += 1
  else:
    acima61 += 1

print(f"A quantidade de pessoas ate 15 anos é {ate_15}\nA quantidade de pessoas entre 16 ate 30 anos é {de16_ate30}\nA quantidade de pessoas entre 31 ate 45 anos é {de31_ate45}\nA quantidade de pessoas entre 46 ate 60 anos é {de46_ate60}\nA quantidade de pessoas acima de 61 anos é {acima61}\n")

"""# 15. Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

base = int(input("Digite o valor base: "))
exponente = int (input("Digite o exponente"))
result = 1

for i in range(exponente):
  if base == 1:
    result = base
  else:
    result *= base

print(f"Resultado {result}")

"""# 16. Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário. O programa deverá mostrar também o número de divisões que ele executou para encontrar os números primos. Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados."""

n = int(input("Digite um numero: "))

for testnumero in range(2, n+1):
  for divisornumero in range (1, n+1):
    print(f"{testnumero} / {divisornumero} = {testnumero/(divisornumero / +1)} com o resto {testnumero%(divisornumero+1)}")
    if testnumero % (divisornumero+1) == 0:
      if 1 != divisornumero+1 != testnumero:
        print("Nao e primo\n")
        break
      elif divisornumero+1 == testnumero:
        print("Numero nao e primo\n")