# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i7U116jneJM99dy8m3OeMfmt8r9Qoe67

# 1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido
"""

verific = True

while verific == True :
  nota = int(input("Insira uma nota entre 0 e 10: "))
  if nota >= 0 and nota <= 10 :
   print("Nota armazenada")
   verific = False

  else :
   print("Insira uma nota válida!")

"""# 2. Faça um programa que calcule o mostre a média aritmética de N notas."""

quantidadeNotas = float(input("Digite quantas notas serao utilizadas: "))
n = 0
soma_notas = 0

while n < quantidadeNotas:
 nota = float(input("Digite a nota: "))
 soma_notas += nota
 n += 1

media = soma_notas / quantidadeNotas
print(f"A média será: {media}")

"""# 3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

verific = True

while verific == True :
  nome_usuario = str(input("Insira o nome de usuario\n"))
  nome_senha = str(input("Insira a sua senha\n"))
  if nome_usuario != nome_senha:
    print("Acesso permitido")
    verific = False

  else :
    print("Nome e senha iguais nao é permitido, por favor repita seus dados!")

"""# 4. Um funcionário de uma empresa recebe aumento salarial anualmente. Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário."""

salario = float(input("Digite o salário inicial do funcionário em 1995: R$ "))
porcentagem = 1.5 / 100
ano = 1996
ano_atual = int(input("Insira o ano atual: "))

while ano < ano_atual:
    salario *= 1 + porcentagem
    porcentagem *= 2
    ano += 1
    print(f"O salário no ano de {ano} é de {salario}")

"""# 5. Faça um programa que leia e valide as seguintes informações:
#  Nome: maior que 3 caracteres;
#  Idade: entre 0 e 150;
#  Salário: maior que zero;
#  Sexo: 'f' ou 'm';
#  Estado Civil: 's', 'c', 'v', 'd';
"""

verific = True

while verific == True :
  nome = str(input("Insira seu nome(maior que 3 caracteres) "))
  if len(nome) >= 3 :
    idade = int(input("Insira sua idade(entre 0 e 150) "))
    if idade >= 0 and idade <= 150 :
      salario = float(input("Insira salario(maior do que 0) "))
      if salario >= 0 :
        sexo = str(input("Insira seu sexo [f] [m] "))
        if sexo == "m" or sexo == "f" :
          estCivil = str(input("Insira seu estado civil [s] [c] [v] [d] "))
          if estCivil == "s" or estCivil == "c" or estCivil == "v" or estCivil == "d" :
            print("Informacoes armazenadas")
            verific = False

  else :
   print("Insira valores validos!")

"""# 6. Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

paisA = 80000
paisAPor = 0.03
paisB = 200000
paisBPor = 0.015
ano = 0
verific = True

while paisA < paisB:
  paisA *= 1 + paisAPor
  paisB *= 1 + paisBPor
  ano += 1
print(f"Sera necessario {ano} anos para o país A ultrapassar o país B")

"""# 7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120"""

numero = int(input("Fatorial de: ") )

resultado = 1
contador = 1

while contador <= numero:
    resultado *= contador
    contador += 1

print(f"O fatorial do {numero} será {resultado}")

"""# 8. Faça um programa que solicite ao usuário números indefinidamente até que ele digite 0. Em seguida, o programa deve imprimir a média dos números digitados."""

verific = True
soma = 0
quantidade = 0

while verific == True :
  nota = int(input("Insira o numero 0\n"))
  if nota == 0 :
    verific = False
  if nota != 0:
    soma += nota
    quantidade += 1
    media = soma / quantidade
print(f"A media dos numeros inseridos será {media}")

"""# 9. A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um
# programa capaz de gerar a série até o n−ésimo termo.
"""

n_numeros = 50
contador = 0
primeiro = 1
segundo = 1
soma = 0

while contador < n_numeros:
  print(primeiro)
  soma = primeiro + segundo
  primeiro = segundo
  segundo = soma
  contador +=1

"""# 10. O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e agora possui uma loja de conveniências. Faça um programa que implemente uma caixa registradora rudimentar.
#  O programa deverá receber um número desconhecido de valores referentes aos preços das mercadorias. Um valor zero deve ser informado pelo operador para indicar o final da compra.
#  O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu, para então calcular e mostrar o valor do troco. Após esta operação, o programa deverá voltar ao ponto inicial, para registrar a próxima compra.
#  A saída deve ser conforme o exemplo abaixo:
#  Lojas Tabajara
#  Produto 1: R 2.20
#  Produto 2: R 5.80
#  Produto 3: R 0
#  Total: R 9.00
#  Dinheiro: R 20.00
#  Troco: R 11.00
"""

print("Lojas Tabajara")
print("")
total = 0
produto = 0
valor = 0
resu_final = 0

while True :
  produto += 1
  valor = float(input(f"Produto {produto}: R$"))

  if valor == 0 :
    break
  total += valor

  if resu_final < 0 :
    print("Dinheiro insuficiente")


print(f"O total da compra foi R${total:.2f}")
carteira = float(input("Insira seu dinheiro: "))
resu_final = carteira - total
print(f"Seu troco é de {resu_final}")

"""# 11. O cardápio de uma lanchonete é o seguinte:

"""

total = 0
quantidade = 0
verific = True

p100 = 1.20
p101 = 1.30
p102 = 1.50
p103 = 1.20
p104 = 1.30
p105 = 1.00

print("Produto              Codigo            Preco\nCachorro Quente      100 RS            1,20\nBauru Simples        101 RS            1,30\nBauru com ovo        102 RS            1,50\nHambúrguer           103 RS            1,20\nCheeseburguer        104 S             1,30\nRefrigerante         105 RS            1,00")

while produto != 0:
  produto = int(input("Digite qual o codigo do produto ou 0 para finalizar o programa: "))
  quantidade = int(input("Digite a quantidade de produtos: "))

  if produto == 0 :
    verific = False

  if produto == 100:
    preco = quantidade * p100
    print(f"Ficou em um total de RS{preco}")

  elif produto == 101:
    preco = quantidade * p101
    print(f"Ficou em um total de RS{preco}")

  elif produto == 102:
    preco = quantidade * p102
    print(f"Ficou em um total de RS{preco}")

  elif produto == 103:
    preco = quantidade * p103
    print(f"Ficou em um total de RS{preco}")

  elif produto == 104:
    preco = quantidade * p104
    print(f"Ficou em um total de RS{preco}")

  elif produto == 105:
    preco = quantidade * p105
    print(f"Ficou em um total de RS{preco}")

print("")

"""# 12. Em uma eleição presidencial existem quatro candidatos. Os votos são informados por meio de código"""

votosCand1 = 0
votosCand2 = 0
votosCand3 = 0
votosCand4 = 0
nulo = 0
branco = 0

total_votos = 0

print("     Candidato 1 - 1 \n     Candidato 2 - 2 \n      Candidato 3 - 3 \n    Candidato 4 - 4 \n    Nulo - 5 \n     Branco - 6")

while True:
  voto = int(input("Digite o código do candidato ou 0 para encerrar o programa: "))

  if voto == 0:
    break

  if voto == 1:
    votosCand1 += 1

  elif voto == 2:
    votosCand2 += 1

  elif voto == 3:
    votosCand3 += 1

  elif voto == 4:
    votosCand4 += 1

  elif voto == 5:
    nulo += 1

  elif voto == 6:
    branco += 1

  total_votos += 1

percNulo = (nulo / total_votos) * 100
percBranco = (branco / total_votos) * 100

print(f" candidato 1: {votosCand1} \n candidato 2: {votosCand2} \n candidato 3: {votosCand3} \n candidato 4: {votosCand4} \n nulo: {nulo} com percentual de {percNulo:.2f}% sobre o total \n branco: {branco} com percentual de {percBranco:.2f}% sobre o total\n ")